steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--project", "$PROJECT_ID", "--version", "hello", "--no-promote"]
timeout: "600s"